services:
  db:
    image: mysql:8
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1s
      timeout: 20s
      retries: 10
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app

  web:
    build: .
    command: python app.py
    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: db
      DB_NAME: db
    volumes:
      - .:/app
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  db-data:
